/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PropiedadesRouteImport } from './routes/propiedades'
import { Route as AgenteRouteImport } from './routes/agente'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropiedadesIndexRouteImport } from './routes/propiedades.index'
import { Route as PropiedadesIdRouteImport } from './routes/propiedades.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadesRoute = PropiedadesRouteImport.update({
  id: '/propiedades',
  path: '/propiedades',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenteRoute = AgenteRouteImport.update({
  id: '/agente',
  path: '/agente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadesIndexRoute = PropiedadesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PropiedadesRoute,
} as any)
const PropiedadesIdRoute = PropiedadesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PropiedadesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agente': typeof AgenteRoute
  '/propiedades': typeof PropiedadesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/propiedades/$id': typeof PropiedadesIdRoute
  '/propiedades/': typeof PropiedadesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agente': typeof AgenteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/propiedades/$id': typeof PropiedadesIdRoute
  '/propiedades': typeof PropiedadesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agente': typeof AgenteRoute
  '/propiedades': typeof PropiedadesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/propiedades/$id': typeof PropiedadesIdRoute
  '/propiedades/': typeof PropiedadesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agente'
    | '/propiedades'
    | '/sitemap.xml'
    | '/propiedades/$id'
    | '/propiedades/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agente' | '/sitemap.xml' | '/propiedades/$id' | '/propiedades'
  id:
    | '__root__'
    | '/'
    | '/agente'
    | '/propiedades'
    | '/sitemap.xml'
    | '/propiedades/$id'
    | '/propiedades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenteRoute: typeof AgenteRoute
  PropiedadesRoute: typeof PropiedadesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedades': {
      id: '/propiedades'
      path: '/propiedades'
      fullPath: '/propiedades'
      preLoaderRoute: typeof PropiedadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agente': {
      id: '/agente'
      path: '/agente'
      fullPath: '/agente'
      preLoaderRoute: typeof AgenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedades/': {
      id: '/propiedades/'
      path: '/'
      fullPath: '/propiedades/'
      preLoaderRoute: typeof PropiedadesIndexRouteImport
      parentRoute: typeof PropiedadesRoute
    }
    '/propiedades/$id': {
      id: '/propiedades/$id'
      path: '/$id'
      fullPath: '/propiedades/$id'
      preLoaderRoute: typeof PropiedadesIdRouteImport
      parentRoute: typeof PropiedadesRoute
    }
  }
}

interface PropiedadesRouteChildren {
  PropiedadesIdRoute: typeof PropiedadesIdRoute
  PropiedadesIndexRoute: typeof PropiedadesIndexRoute
}

const PropiedadesRouteChildren: PropiedadesRouteChildren = {
  PropiedadesIdRoute: PropiedadesIdRoute,
  PropiedadesIndexRoute: PropiedadesIndexRoute,
}

const PropiedadesRouteWithChildren = PropiedadesRoute._addFileChildren(
  PropiedadesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenteRoute: AgenteRoute,
  PropiedadesRoute: PropiedadesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
